require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/packagetask'
require 'find'

# Globals

PKG_NAME = 'pocogese_plugin'
PKG_VERSION = '0.0.1'

PKG_FILES = ['README',  'init.rb', 'install.rb' , 'CHANGELOG', 'MIT-LICENSE' ]
PKG_DIRECTORIES = [ 'lib/', 'tasks/', 'test/' , '/apptasks' ]
PKG_DIRECTORIES.each do |dir|
  Find.find(dir) do |f|
    if FileTest.directory?(f) and f =~ /\.svn/
      Find.prune
    else
      PKG_FILES << f
    end
  end
end

# Tasks

task :package
Rake::PackageTask.new(PKG_NAME, PKG_VERSION) do |p|
        p.need_tar = true
        p.package_files = PKG_FILES
end

desc 'Default: run unit tests.'
task :default => :test

desc 'Test the pocogese plugin.'
Rake::TestTask.new(:test) do |t|
  t.libs << 'lib'
  t.pattern = 'test/**/*_test.rb'
  t.verbose = true
end

desc 'Generate documentation for the pocogese plugin.'
Rake::RDocTask.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title    = 'Pocogese'
  rdoc.options << '--line-numbers' << '--inline-source'
  rdoc.rdoc_files.include('README')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

# "Gem" part of the Rakefile
begin
        require 'rake/gempackagetask'

        spec = Gem::Specification.new do |s|
                s.platform = Gem::Platform::RUBY
                s.summary = "Pocogese is a Rails plugin that extends REST with Command-Reply-Selection support."
                s.name = PKG_NAME
                s.version = PKG_VERSION
                s.requirements << 'none'
                s.files = PKG_FILES
                s.description = "Pocogese provides Command-Reply-Selection support for building RIA's using Adobe Flex."
        end

        task :package_gem
        Rake::GemPackageTask.new(spec) do |pkg|
                pkg.need_zip = true
                pkg.need_tar = true
        end
rescue LoadError
end